### ISSUE TITLE
not sure what happened in this crash

### ISSUE THREAD

**Issue by stw222** [gbl/EasierCrafting#10]
https://pastebin.com/j1NX55Bw

I just pressed E after having just logged on to the server. I was in survival.

rift mods used:
https://i.imgur.com/fzCs9tf.png
I have forge mods in my mods folder but those aren't loaded when i use rift.

**Comment by gbl** [comment]
Seems like an issue that's similar to #8. The "after having just logged on to the server" helped me understand the root cause, actually; at this point, the client is still busy loading chunks so creating the search pattern can be a bit delayed. And if you type a key after opening the gui, but before the search pattern box gets created, you get this crash. The #8 crash was in the "a character gets typed" code, while this one is in the "a non-character-key, like escape or return, gets pressed" code.
