### ISSUE TITLE
[Suggestions]Allow Mass Crafting

### ISSUE THREAD

**Issue by Neubulae** [gbl/EasierCrafting#22]
I didn't like repeatedly clicking, can you add a functionality that allows you to craft until the items are fully exhausted? Not just craft up to 64 items in the grid

**Comment by Madis0** [comment]
#6

**Comment by gbl** [comment]
Sorry, I tried getting this to work for quite some time, but couldn't. This is mainly because I can't reliably determine what the inventory is going to look like, before the server responds to the first craft, so I can't really send the next batch of clicks before the first craft is finished. Trying leads to lots of desync, and sometimes crafting the wrong item because the grid doesn't get filled the way it should.

**Comment by Neubulae** [comment]
It's OK, thanks for the support!
