### ISSUE TITLE
Suggestion: mouse wheel support

### ISSUE THREAD

**Issue by MeeniMc** [gbl/EasierCrafting#32]
It appears that the only way to scroll up-down in the list of possible recipes is by using the two ugly red arrows at the top of the list area.

Mouse wheel support would be more natural, imo, and greatly improve the mod. 

Thanks for a great mod.

**Comment by gbl** [comment]
Oh dear! Scrolling was in the mod, once, but seems to have broken in the long list of ports from Forge 1.10 to Rift 1.13 to Fabric 1.16, and I never noticed, because I'm using a lower GUI scale.  (I don't recommend having auto highest anyway, as there won't be enough space below the crafting gui to show all ingredients).

Anyway, I just uploaded 1.6.5, which reenables mouse scrolling, replaces the ugly arrows with slightly less ugly ones, and includes turkish and trad. chinese translations, supplied by two users.

**Comment by MeeniMc** [comment]
Well that was quick! Thanks, just tested all good.
