### ISSUE TITLE
Can't Open Crafting Table With Mod Active. 

### ISSUE THREAD

**Issue by TechnologicApe** [gbl/EasierCrafting#4]
I recently installed your mod and used it on a 1.11.2 world. I've since deleted that world and started a new one but now I can't open my crafting table. No new mods have been installed.

**Comment by gbl** [comment]
Did you use the 1.12 version of the mod, or the 1.11(.2) version?

The 1.12 version has an option to disable the new 1.12 minecraft-internal craftbook. Having this option enabled on 1.11(.2) might cause an exception because it tries to do things that just aren't there on 1.11.

Please upload your log file somewhere, or paste the relevant part (the exception that probably happens when you open a craft table) here  or link it on pastebin.

**Comment by TechnologicApe** [comment]
I was using a 1.11.2 version on 1.11.2 Minecraft. It seems to work fine as long I have Thermal Expansion installed.
