### ISSUE TITLE
the loom  banner letters

### ISSUE THREAD

**Issue by frankhta** [gbl/EasierCrafting#43]
for some reason the letter B in the loom does not work properly

and is there any way to add numbers to the loom ty

**Comment by gbl** [comment]
The letter B needs a Mojang "Thing" banner pattern to work. (Unfortunately, this isn't displayed nicely in the gui).
I wasn't able to find good patterns for the numbers, that's why I didn't include them. But you can save your own patterns by putting a finished banner in the loom and pressing the save button.
