### ISSUE TITLE
Dispenser crafting glitchy 

### ISSUE THREAD

**Issue by H3XDaemon** [gbl/EasierCrafting#45]
Dispensor generally disappeared from the recipe
I have confirmed that all the ingredients are complete
The bow is also just crafted and in good condition without enchantment
I'm not sure if this is a bug or if I'm using it in the wrong way

**Comment by H3XDaemon** [comment]
I'm using 1.17.1-fabric0.36.1-1.7 version

**Comment by H3XDaemon** [comment]
![image](https://user-images.githubusercontent.com/42803553/136691027-a4aee755-fd68-468e-8d5c-1ad88a5e6475.png)

**Comment by H3XDaemon** [comment]
I just found out the server I playing have a plugin will auto add a nbt key to the bow
Is it possible to "fix" this?
Maybe make an option to ignore whether the bow has an nbt value?

**Comment by H3XDaemon** [comment]
![image](https://user-images.githubusercontent.com/42803553/136692234-828af886-7ff9-4553-aec8-a9ac01b41f72.png)

**Comment by gbl** [comment]
The problem is, it's not bow specific; I generally don't allow crafting with items that have NBT values. This is in the canActAsIngredient method in https://github.com/gbl/EasierCrafting/blob/fabric_1_17/src/main/java/de/guntram/mcmod/easiercrafting/RecipeBook.java#L920 - a Damage tag that has value 0 is ok, and also a BlockEntityTag on shulker boxes, so shulkers can be dyed even with content / when they ever had content.

I definitely don't want to generally allow crafting with items that have tags, or people will complain about accidentially crafting trapped chests and using their vote keys, or anything else that uses nonstandard, vote-reward items.

And since `PublicBukkitValues` isn't even an invention of this mod (it's used by the spigot `PersistentDataHolder` interface), ignoring this is likely to ignore other plugins' extra data as well, so you'd have to ignore `blockllamaplugin:minecraft-bow-nbt-key` within `PublicBukkitValues`. And there could even be several tags within `PublicBukkitValues` where only some need to be ignored .. This complexity would be a nightmare for making it configurable.

Now, as bows don't stack, you can only craft one dispenser at a time anyway. So I suggest you right-click the dropper, shift-click a bow, then shift-click the output stack, and repeat as needed. Still 3 clicks instead of 1, but, given the situation, probably the easiest solution.

**Comment by H3XDaemon** [comment]
Okay, I understand
Thank you very much for your reply and this very useful plugin!
