### ISSUE TITLE
one click

### ISSUE THREAD

**Issue by ghost** [gbl/EasierCrafting#6]
Hi, I'd like to use this mod on a private mod pack with my friends and me. If you could, can you make a private version of this mod for when CTRL-clicking on a recipe in the GUI, it will craft everything it can in the inventory?
So instead of holding SHIFT and clicking multiple times, you hold CTRL and press once.

Thanks.

**Comment by gbl** [comment]
Sorry, I tried getting this to work for quite some time, but couldn't. This is mainly because I can't reliably determine what the inventory is going to look like, before the server responds to the first craft, so I can't really send the next batch of clicks before the first craft is finished. Trying leads to lots of desync, and sometimes crafting the wrong item because the grid doesn't get filled the way it should.
