### ISSUE TITLE
Devide by zero crash when joining server

### ISSUE THREAD

**Issue by stw222** [gbl/EasierCrafting#7]
Crash report:

[https://pastebin.com/bkJryevE](https://pastebin.com/bkJryevE)

**Comment by stw222** [comment]
not sure if this error is any different but it seems to do it when opening the inventory too. i think that joining the server error was a one off.

[https://pastebin.com/AyF3QWz3](https://pastebin.com/AyF3QWz3)

**Comment by gbl** [comment]
Did you happen to be in creative mode when you got those crashes? I was able to reproduce them when I was in creative, but not in survival.

Anyway, the reason is the mod calculates how many items fit in a display row, and the divide by zero error comes from that number being 0. This number depends on Gui size (with maximum/auto size there's less space to display stuff next to the original Gui), but I wasn't able to get it to zero no matter how I scaled the screen.

I'm forcing it to be at least 2 now, so there shouldn't be any crashes - and I hope there won't be any items offscreen either. Could you please test the jar file at https://github.com/gbl/EasierCrafting/releases/tag/1.13.2-1.3beta2 if it works for you, and if the screen looks weird, send me a screenshot? Thanks!

**Comment by stw222** [comment]
Ill test it when i wake up in the morning. Im pretty sure i wasnt in creative but i was on a server with /fly. I also have a few other mods that add stuff to the screen. Ill list them, also, when i wake up in the morning. 

Also my gui size i think is 3. Its whatever the biggest is without it being on auto on a 1080p 16:9 screen

**Comment by stw222** [comment]
seems to work after 5 minutes of use. just in case your mod was conflicting with something, these are the mods in using: 

![Imgur](https://i.imgur.com/bVmdh00.png)
